version: '3.4'

services:
  azureexample:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__SQL=Server=DB;Database=AppDB;User Id=sa;Password=OyzTFUUb5Ri7cjP@4r;TrustServerCertificate=True;
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  DB:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
     - MSSQL_SA_PASSWORD=OyzTFUUb5Ri7cjP@4r
     - ACCEPT_EULA=Y 
    ports:
     - "3306:3306" 
 